CREATE TABLE "HIS_RS"."HIS_SAMPLE_DESK" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATE_TIME" NUMBER(14,0), 
	"MODIFY_TIME" NUMBER(14,0), 
	"CREATOR" VARCHAR2(50 BYTE), 
	"MODIFIER" VARCHAR2(50 BYTE), 
	"APP_CREATOR" VARCHAR2(50 BYTE), 
	"APP_MODIFIER" VARCHAR2(50 BYTE), 
	"IS_ACTIVE" NUMBER(2,0) DEFAULT 1, 
	"IS_DELETE" NUMBER(2,0) DEFAULT 0, 
	"GROUP_CODE" VARCHAR2(50 BYTE), 
	"SAMPLE_DESK_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"SAMPLE_DESK_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SAMPLE_ROOM_ID" NUMBER(19,0), 
	 CONSTRAINT "HIS_SAMPLE_DESK_CHK1" CHECK (SAMPLE_ROOM_ID IS NOT NULL) ENABLE, 
	 CONSTRAINT "HIS_SAMPLE_DESK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS"  ENABLE, 
	 CONSTRAINT "HIS_SAMPLE_DESK_FK1" FOREIGN KEY ("SAMPLE_ROOM_ID")
	  REFERENCES "HIS_RS"."HIS_SAMPLE_ROOM" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS"   NO INMEMORY ;

   COMMENT ON COLUMN "HIS_RS"."HIS_SAMPLE_DESK"."SAMPLE_DESK_CODE" IS 'Ma o';
   COMMENT ON COLUMN "HIS_RS"."HIS_SAMPLE_DESK"."SAMPLE_DESK_NAME" IS 'Ten o';

  CREATE INDEX "HIS_RS"."HIS_SAMPLE_DESK_INDEX1" ON "HIS_RS"."HIS_SAMPLE_DESK" ("SAMPLE_ROOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS" ;

   CREATE SEQUENCE  "HIS_RS"."HIS_SAMPLE_DESK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23758226 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HIS_RS"."HIS_SAMPLE_DESK_1" BEFORE INSERT ON HIS_SAMPLE_DESK FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
v_time NUMBER(14) := 0;
BEGIN
	SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) INTO v_time FROM DUAL;
	:new.CREATE_TIME := v_time;
	:new.MODIFY_TIME := v_time;
	:new.MODIFIER := :new.CREATOR;
	:new.APP_MODIFIER := :new.APP_CREATOR;
	IF INSERTING AND ((:new.ID IS NULL) OR (:new.ID = 0)) THEN
		SELECT HIS_SAMPLE_DESK_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
		:new.ID := v_newVal;
	END IF;
	IF INSERTING AND (:new.IS_ACTIVE IS NULL) THEN
		:new.IS_ACTIVE := 1;
	END IF;
	IF INSERTING AND (:new.IS_DELETE IS NULL) THEN
		:new.IS_DELETE := 0;
	END IF;
END;
/
ALTER TRIGGER "HIS_RS"."HIS_SAMPLE_DESK_1" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HIS_RS"."HIS_SAMPLE_DESK_2" BEFORE UPDATE ON HIS_SAMPLE_DESK FOR EACH ROW
DECLARE 
V_TIME NUMBER(14) := 0;
BEGIN
	SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) INTO V_TIME FROM DUAL;
	:NEW.MODIFY_TIME := V_TIME;
END;
/
ALTER TRIGGER "HIS_RS"."HIS_SAMPLE_DESK_2" ENABLE;


CREATE TABLE "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATE_TIME" NUMBER(14,0), 
	"MODIFY_TIME" NUMBER(14,0), 
	"CREATOR" VARCHAR2(50 BYTE), 
	"MODIFIER" VARCHAR2(50 BYTE), 
	"APP_CREATOR" VARCHAR2(50 BYTE), 
	"APP_MODIFIER" VARCHAR2(50 BYTE), 
	"IS_ACTIVE" NUMBER(2,0), 
	"IS_DELETE" NUMBER(2,0), 
	"GROUP_CODE" VARCHAR2(50 BYTE), 
	"TREATMENT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"SAMPLE_ROOM_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"SAMPLE_DESK_ID" NUMBER(19,0), 
	"TDL_IS_PRIORITY" NUMBER(2,0), 
	"TDL_PATIENT_TYPE_ID" NUMBER(19,0), 
	"TDL_TREATMENT_TYPE_ID" NUMBER(19,0), 
	"CALL_TIME" NUMBER(14,0), 
	"VIR_CREATE_DATE" NUMBER GENERATED ALWAYS AS ("CREATE_TIME"-MOD("CREATE_TIME",1000000)) VIRTUAL ,
	 CONSTRAINT "HIS_TREATMENT_SAMPLE_DESK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS"  ENABLE, 
	 CONSTRAINT "HIS_TREATMENT_SAMPLE_DESK_CHK1" CHECK (LENGTH(CALL_TIME) = 14) ENABLE,
	 CONSTRAINT "HIS_TREATMENT_SAMPLE_DESK_FK1" FOREIGN KEY ("TREATMENT_ID")
	  REFERENCES "HIS_RS"."HIS_TREATMENT" ("ID") ENABLE, 
	 CONSTRAINT "HIS_TREATMENT_SAMPLE_DESK_FK2" FOREIGN KEY ("SAMPLE_ROOM_ID")
	  REFERENCES "HIS_RS"."HIS_SAMPLE_ROOM" ("ID") ENABLE, 
	 CONSTRAINT "HIS_TREATMENT_SAMPLE_DESK_FK3" FOREIGN KEY ("SAMPLE_DESK_ID")
	  REFERENCES "HIS_RS"."HIS_SAMPLE_DESK" ("ID") ENABLE, 
	 CONSTRAINT "HIS_TREATMENT_SAMPLE_DESK_FK4" FOREIGN KEY ("TDL_PATIENT_TYPE_ID")
	  REFERENCES "HIS_RS"."HIS_PATIENT_TYPE" ("ID") ENABLE, 
	 CONSTRAINT "HIS_TREATMENT_SAMPLE_DESK_FK5" FOREIGN KEY ("TDL_TREATMENT_TYPE_ID")
	  REFERENCES "HIS_RS"."HIS_TREATMENT_TYPE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS"   NO INMEMORY ;

  CREATE INDEX "HIS_RS"."HIS_TMT_SAMPLE_DESK_INDEX1" ON "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK" ("TREATMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS" ;

  CREATE INDEX "HIS_RS"."HIS_TMT_SAMPLE_DESK_INDEX2" ON "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK" ("SAMPLE_ROOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS" ;

  CREATE INDEX "HIS_RS"."HIS_TMT_SAMPLE_DESK_INDEX3" ON "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK" ("SAMPLE_DESK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS" ;

  CREATE INDEX "HIS_RS"."HIS_TMT_SAMPLE_DESK_INDEX4" ON "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK" ("TDL_PATIENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS" ;

  CREATE INDEX "HIS_RS"."HIS_TMT_SAMPLE_DESK_INDEX5" ON "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK" ("VIR_CREATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS" ;

  CREATE INDEX "HIS_RS"."HIS_TMT_SAMPLE_DESK_INDEX6" ON "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK" ("TDL_TREATMENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HIS_RS" ;

   CREATE SEQUENCE  "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23758226 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK_1" BEFORE INSERT ON HIS_TREATMENT_SAMPLE_DESK FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
v_time NUMBER(14) := 0;
BEGIN
	SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) INTO v_time FROM DUAL;
	:new.CREATE_TIME := v_time;
	:new.MODIFY_TIME := v_time;
	:new.MODIFIER := :new.CREATOR;
	:new.APP_MODIFIER := :new.APP_CREATOR;
	IF INSERTING AND ((:new.ID IS NULL) OR (:new.ID = 0)) THEN
		SELECT HIS_TREATMENT_SAMPLE_DESK_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
		:new.ID := v_newVal;
	END IF;
	IF INSERTING AND (:new.IS_ACTIVE IS NULL) THEN
		:new.IS_ACTIVE := 1;
	END IF;
	IF INSERTING AND (:new.IS_DELETE IS NULL) THEN
		:new.IS_DELETE := 0;
	END IF;
END;


/
ALTER TRIGGER "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK_1" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK_2" BEFORE UPDATE ON HIS_TREATMENT_SAMPLE_DESK FOR EACH ROW
DECLARE 
V_TIME NUMBER(14) := 0;
BEGIN
	SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) INTO V_TIME FROM DUAL;
	:NEW.MODIFY_TIME := V_TIME;
END;
/
ALTER TRIGGER "HIS_RS"."HIS_TREATMENT_SAMPLE_DESK_2" ENABLE;
/
CREATE OR REPLACE VIEW V_HIS_TREATMENT_SAMPLE_DESK
AS SELECT TSD.*,
TREA.TREATMENT_CODE,
TREA.TDL_PATIENT_CODE,
TREA.TDL_PATIENT_NAME,
TREA.TDL_PATIENT_DOB,
TREAT.TREATMENT_TYPE_NAME,
PTT.PATIENT_TYPE_NAME,
SAR.SAMPLE_ROOM_NAME,
SAD.SAMPLE_DESK_NAME,
(CASE WHEN PAID = PAYMENT THEN 1 END) IS_PAID,
(CASE WHEN PAYMENT = PAYMENT_BHYT THEN 1 END) IS_BHYT,
(CASE WHEN PAID = PAYMENT OR PAYMENT = PAYMENT_BHYT THEN 1 END) IS_BHYT_OR_PAID
FROM HIS_TREATMENT_SAMPLE_DESK TSD
JOIN HIS_TREATMENT TREA ON TREA.ID = TSD.TREATMENT_ID
JOIN HIS_SAMPLE_ROOM SAR ON SAR.ID = TSD.SAMPLE_ROOM_ID
JOIN HIS_PATIENT_TYPE PTT ON PTT.ID = TSD.TDL_PATIENT_TYPE_ID
JOIN HIS_TREATMENT_TYPE TREAT ON TREAT.ID = TREA.TDL_TREATMENT_TYPE_ID
LEFT JOIN HIS_SAMPLE_DESK SAD ON SAD.ID = TSD.SAMPLE_DESK_ID
LEFT JOIN LATERAL
(SELECT /*+ NO_RESULT_CACHE */SUM(SSB.PRICE) PAID, SUM(SS.VIR_TOTAL_PATIENT_PRICE) PAYMENT, SUM(SS.VIR_TOTAL_PATIENT_PRICE_BHYT) PAYMENT_BHYT 
FROM HIS_SERE_SERV SS
JOIN HIS_SERVICE_REQ SR ON SR.ID = SS.SERVICE_REQ_ID
LEFT JOIN HIS_SERE_SERV_BILL SSB ON SSB.SERE_SERV_ID = SS.ID AND SSB.TDL_TREATMENT_ID = TSD.TREATMENT_ID
WHERE SS.IS_DELETE=0 AND SS.IS_NO_EXECUTE IS NULL AND SSB.IS_CANCEL IS NULL
AND SR.IS_DELETE=0 AND SR.IS_NO_EXECUTE IS NULL
AND SR.SAMPLE_ROOM_ID = TSD.SAMPLE_ROOM_ID
AND SR.TREATMENT_ID = TSD.TREATMENT_ID) ON 1=1
WHERE TSD.IS_DELETE = 0;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HIS_RS"."HIS_SERVICE_REQ_101" BEFORE INSERT OR UPDATE ON HIS_SERVICE_REQ FOR EACH ROW
DECLARE 
BEGIN
 IF :NEW.SAMPLE_ROOM_ID IS NOT NULL AND (:OLD.SAMPLE_ROOM_ID IS NULL OR :OLD.SAMPLE_ROOM_ID <> :NEW.SAMPLE_ROOM_ID) THEN
   INSERT INTO HIS_TREATMENT_SAMPLE_DESK (TREATMENT_ID,SAMPLE_ROOM_ID,TDL_IS_PRIORITY,TDL_PATIENT_TYPE_ID,TDL_TREATMENT_TYPE_ID) 
   SELECT :NEW.TREATMENT_ID,:NEW.SAMPLE_ROOM_ID,:NEW.PRIORITY,:NEW.TDL_PATIENT_TYPE_ID,:NEW.TDL_TREATMENT_TYPE_ID FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HIS_TREATMENT_SAMPLE_DESK WHERE TREATMENT_ID = :NEW.TREATMENT_ID AND SAMPLE_ROOM_ID = :NEW.SAMPLE_ROOM_ID AND SAMPLE_DESK_ID IS NULL);
 END IF;
END;
/
ALTER TRIGGER "HIS_RS"."HIS_SERVICE_REQ_101" ENABLE;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HIS_RS"."L_HIS_SAMPLE_DESK_COUNTER" ("ID", "SAMPLE_DESK_CODE", "SAMPLE_DESK_NAME", "IS_ACTIVE", "BRANCH_ID", "DEPARTMENT_NAME", "DEPARTMENT_ID", "SAMPLE_ROOM_NAME", "SAMPLE_ROOM_ID", "NUM_ORDER", 
	 CONSTRAINT "L_HIS_SAMPLE_DESK_COUNTER_" PRIMARY KEY ("ID") DISABLE) AS 
  SELECT SD.ID,SD.SAMPLE_DESK_CODE,SD.SAMPLE_DESK_NAME,SD.IS_ACTIVE,DT.BRANCH_ID,DT.DEPARTMENT_NAME,
RO.DEPARTMENT_ID,SAR.SAMPLE_ROOM_NAME,SD.SAMPLE_ROOM_ID,
(SELECT COUNT(1) FROM HIS_TREATMENT_SAMPLE_DESK TSD WHERE TSD.SAMPLE_DESK_ID = SD.ID AND TSD.IS_DELETE = 0 AND TSD.VIR_CREATE_DATE = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD') || '000000')) NUM_ORDER
FROM HIS_SAMPLE_DESK SD
JOIN HIS_SAMPLE_ROOM SAR ON SD.SAMPLE_ROOM_ID = SAR.ID
JOIN HIS_ROOM RO ON SAR.ROOM_ID = RO.ID
JOIN HIS_DEPARTMENT DT ON DT.ID = RO.DEPARTMENT_ID;
insert into his_sample_desk (sample_desk_code,sample_desk_name,sample_room_id) values('01','Ô số 1',(select id from his_sample_room where sample_room_code='02'));
insert into his_sample_desk (sample_desk_code,sample_desk_name,sample_room_id) values('02','Ô số 2',(select id from his_sample_room where sample_room_code='02'));
insert into his_sample_desk (sample_desk_code,sample_desk_name,sample_room_id) values('03','Ô số 3',(select id from his_sample_room where sample_room_code='02'));
insert into his_sample_desk (sample_desk_code,sample_desk_name,sample_room_id) values('04','Ô số 4',(select id from his_sample_room where sample_room_code='02'));
insert into his_sample_desk (sample_desk_code,sample_desk_name,sample_room_id) values('05','Ô số 5',(select id from his_sample_room where sample_room_code='02'));
commit;
insert into his_config (key,value,default_value,description) select replace(key,'EXE.','SAMPLE.'),value,default_value,description from his_config where key in ('EXE.WAITING_SCREEN.ROOM_NAME.COLOR_CODES',
'EXE.WAITING_SCREEN.ROOM_NAME.COLOR_CODES',
'EXE.WAITING_SCREEN.USER_NAME.COLOR_CODES',
'EXE.WAITING_SCREEN.BACKGROUND_PARENT.COLOR_CODES',
'EXE.WAITING_SCREEN.ORGANIZATION_NAME.COLOR_CODES',
'EXE.WAITING_SCREEN.BACK_COLOR_GRID_PATIENT.COLOR_CODES',
'EXE.WAITING_SCREEN.BACK_COLOR_GRID_PATIENT_HEADER.COLOR_CODES',
'EXE.WAITING_SCREEN.FORCE_COLOR_GRID_PATIENT_HEADER.COLOR_CODES',
'EXE.WAITING_SCREEN.FORCE_COLOR_GRID_PATIENT_BODY.COLOR_CODES',
'EXE.WAITING_SCREEN.FORCE_COLOR_PAGING.COLOR_CODES',
'EXE.WAITING_SCREEN.FORCE_COLOR_NEW_STATUS.COLOR_CODES',
'EXE.WAITING_SCREEN.TIMER_FOR_AUTO_LOAD_PATIENTS.COLOR_CODES',
'EXE.WAITING_SCREEN.TIMER_FOR_HIGHT_LIGHT_CALL_A_PATIENT',
'EXE.WAITING_SCREEN.WATING_EXAM_NAME_COLOR_CODES',
'EXE.WAITING_SCREEN.WATING_CLS_NAME_COLOR_CODES',
'EXE.WAITING_SCREEN.TIMER_FOR_SET_DATA_TO_GRID_PATIENT');
commit;