//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS.Desktop.LocalStorage.BackendData.V2.EFMODEL
{
    using MOS.EFMODEL.DataModels;
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_SAMPLE_DESK
    {
        public HIS_SAMPLE_DESK()
        {
            this.HIS_TREATMENT_SAMPLE_DESK = new HashSet<HIS_TREATMENT_SAMPLE_DESK>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string SAMPLE_DESK_CODE { get; set; }
        public string SAMPLE_DESK_NAME { get; set; }
        public Nullable<long> SAMPLE_ROOM_ID { get; set; }
    
        public virtual HIS_SAMPLE_ROOM HIS_SAMPLE_ROOM { get; set; }
        public virtual ICollection<HIS_TREATMENT_SAMPLE_DESK> HIS_TREATMENT_SAMPLE_DESK { get; set; }
    }
}
