//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS.Desktop.LocalStorage.BackendData.V2.EFMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_HIS_SERVICE_REQ_101
    {
        public long ID { get; set; }
        public string SERVICE_REQ_CODE { get; set; }
        public string ASSIGN_TURN_CODE { get; set; }
        public long TREATMENT_ID { get; set; }
        public Nullable<long> SAMPLE_ROOM_ID { get; set; }
        public string TDL_SERVICE_CODE { get; set; }
        public string TDL_SERVICE_NAME { get; set; }
        public Nullable<long> PARENT_SERVICE_ID { get; set; }
        public string PARENT_SERVICE_CODE { get; set; }
        public string PARENT_SERVICE_NAME { get; set; }
    }
}
