//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS.Desktop.LocalStorage.BackendData.V2.EFMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_HIS_SAMPLE_DESK_COUNTER
    {
        public long ID { get; set; }
        public string SAMPLE_DESK_CODE { get; set; }
        public string SAMPLE_DESK_NAME { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public long BRANCH_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public long DEPARTMENT_ID { get; set; }
        public string SAMPLE_ROOM_NAME { get; set; }
        public Nullable<long> SAMPLE_ROOM_ID { get; set; }
        public Nullable<decimal> NUM_ORDER { get; set; }
    }
}
